services:
  postgres:
    image: postgres:16-alpine
    container_name: vivaeventos-postgres
    environment:
      POSTGRES_USER: devdb
      POSTGRES_PASSWORD: a1b2c3d4
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    build:
      context: ../../vivaeventos-auth
      dockerfile: Dockerfile
    container_name: vivaeventos-auth
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vivaeventos_auth
      SPRING_DATASOURCE_USERNAME: devdb
      SPRING_DATASOURCE_PASSWORD: a1b2c3d4
      JWT_SECRET: dGhpc0lzQVZlcnlTZWNyZXRLZXlGb3JWYWlhRXZlbnRvc1RoYXROZWVkczUw
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    build:
      context: ../../vivaeventos-gateway
      dockerfile: Dockerfile
    container_name: vivaeventos-gateway
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: dGhpc0lzQVZlcnlTZWNyZXRLZXlGb3JWYWlhRXZlbnRvc1RoYXROZWVkczUw
      AUTH_URI: http://auth:8083
      EVENTS_URI: http://events:8081
      ORDERS_URI: http://orders:8083
    depends_on:
      - auth

  events:
    build:
      context: ../../vivaeventos-events
      dockerfile: Dockerfile
    container_name: vivaeventos-events
    ports:
      - "8084:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vivaeventos_events
      SPRING_DATASOURCE_USERNAME: devdb
      SPRING_DATASOURCE_PASSWORD: a1b2c3d4
      JWT_SECRET: dGhpc0lzQVZlcnlTZWNyZXRLZXlGb3JWYWlhRXZlbnRvc1RoYXROZWVkczUw
    depends_on:
      postgres:
        condition: service_healthy

  orders:
    build:
      context: ../../vivaeventos-orders
      dockerfile: Dockerfile
    container_name: vivaeventos-orders
    ports:
      - "8085:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vivaeventos_orders
      SPRING_DATASOURCE_USERNAME: devdb
      SPRING_DATASOURCE_PASSWORD: a1b2c3d4
      JWT_SECRET: dGhpc0lzQVZlcnlTZWNyZXRLZXlGb3JWYWlhRXZlbnRvc1RoYXROZWVkczUw
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
